server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # React Router: все запросы, кроме статических файлов, отдаём index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}